[Variables]
; Options
ClipAmount = 5

; Styling
BackgroundColor = 0,0,0,50
ContentBackgroundColor = 0,0,0,200
TextColor = 255,255,255
UrlColor = 120,120,255

Width = 1080
Height = 175

FontSize = 10
Font = Garamond
FontWeigth = 400

Margin = 12
BackgroundBorderRadius = 10
BackgroundStrokeWidth = 0

ContentMargin = 5
ContentSpacing = 10
ContentStrokeWidth = 2
ContentBorderRadius = 5
ContentBorderColor = 100,100,100,50
